### ISSUE TITLE
nerd

### ISSUE THREAD

**Issue by NotGoodAtCoding** [NickolasHKraus/COMS-327-E1#1]
Edit: conformed to format

## Bug
you are a nerd

## Environments affected
Real life

## Steps to Reproduce
1. Be alive
2. Talk to you, or interact with you in any way
3. The impression received by the user will be that you are a nerd

## Priority
Critical

**Comment by NickolasHKraus** [comment]
Please use the requisite issue format when submitting tickets against this repository.
